name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  create_app_service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up app service with Bicep file
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment group create --resource-group mtResourceGroup --template-file ./servicedeploy.bicep
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

  retrieve_generated_hostname:
    needs: create_app_service
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve generated hostname
        uses: Azure/cli@v2
        with:
          inlineScript: |
            hostname=$(az staticwebapp show --name ${{ secrets.AZURE_STATIC_WEB_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query defaultHostname -o tsv)
            echo "##vso[task.setvariable variable=generated_hostname;isOutput=true]$hostname"
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        id: retrievegenerated

  build_and_deploy_job:
    needs: retrieve_generated_hostname
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_ACCESS_TOKEN }}_${{ needs.retrieve_generated_hostname.outputs.generated_hostname }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""

  close_pull_request_job:
    needs: retrieve_generated_hostname
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_ACCESS_TOKEN }}_${{ needs.retrieve_generated_hostname.outputs.generated_hostname }}
          action: "close"
