name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  # Deploy Bicep file to create app service
  create_app_service:
  runs-on: ubuntu-latest
  steps:
    - task: AzureCLI@2
      displayName: Set up app service with Bicep file
      inputs:
        azureSubscription: '${{ secrets.AZURE_SUBSCRIPTION }}'  # Assuming secret for subscription ID
        scriptType: 'bash'  # Script type is bash (default for CLI tasks)
        scriptLocation: 'inlineScript'  # Script location is inline
        inlineScript: |
          az deployment group create --resource-group mtResourceGroup --template-file ./servicedeploy.bicep

  
  retrievegenerated:
    needs: create_app_service
    runs-on: ubuntu-latest
    steps:
      - task: AzureCLI@2
        displayName: Retrieve generated hostname
        inputs:
          azureSubscription: '${{ secrets.AZURE_SUBSCRIPTION }}'
          scriptType: 'powershell'  # Script type is PowerShell
          scriptLocation: 'inlineScript'
          inlineScript: |
            $hostname = az staticwebapp show --name ${{ secrets.AZURE_STATIC_WEB_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query defaultHostname -o tsv
            Write-Host "##vso[task.setvariable variable=generated_hostname;isOutput=true]$hostname"
      outputs:
        generated_hostname: ${{ steps.builddeploy.outputs.generated_hostname }}
          

  build_and_deploy_job:
    needs: retrievegenerated
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_ACCESS_TOKEN }}_${{ steps.retrievegenerated.outputs.generated_hostname }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: AZURE_STATIC_WEB_APPS_API_TOKEN_${generated_hostname}
          action: "close"
