name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  create_app_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Authenticate with Azure using Certificate
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Run Azure CLI
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment group create --resource-group mtResourceGroup --template-file $GITHUB_WORKSPACE/.github/workflows/servicedeploy.bicep
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

  retrieve_generated_hostname:
    needs: create_app_service
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Azure using Certificate
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Retrieve generated hostname
        uses: Azure/cli@v2
        with:
          inlineScript: |
            hostname=$(az staticwebapp show --name axusapp --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query defaultHostname -o tsv)
            echo "##vso[task.setvariable variable=generated_hostname;isOutput=true]$hostname"
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        id: retrievegenerated

  build_and_deploy_job:
    needs: retrieve_generated_hostname
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Authenticate and push changes to Azure Static Web Apps
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: deploy to webapp
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ab9c4e2019c919ebf1803d7438e6200c337eae915140d2efe301efee68ac62c65-681d4baa-efba-4556-b733-e80532121f7100f214426
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"